SET NAMES UTF8;
DROP DATABASE IF EXISTS nv_shop;
CREATE DATABASE nv_shop CHARSET=utf8;
USE nv_shop;

CREATE TABLE nv_user(
	uid INT PRIMARY KEY AUTO_INCREMENT,
	uname VARCHAR(32),
	upwd VARCHAR(32),
	phone VARCHAR(11)
);

INSERT INTO nv_user VALUES
(125165,'admin','admin','13512345678'),
(125166,'123456','123456','13156868877');

CREATE TABLE nv_product(
	pid	INT PRIMARY KEY AUTO_INCREMENT,
	pname VARCHAR(35),
	price FLOAT(8,2),
	pic VARCHAR(30),
	pic_s VARCHAR(32)
);
INSERT INTO nv_product VALUES
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"妖精的口袋逃逸灯塔长袖衬衫","654.00","prodoctList_l_-19.jpg","prodoctList_s-19.jpg"),
	(NULL,"拉夏贝尔格子混色polo领衬衫","136.00","prodoctList_l_-20.jpg","prodoctList_s-20.jpg"),
	(NULL,"裂帛时尚花朵印花针织开衫","72.00","prodoctList_l_-21.jpg","prodoctList_s-21.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"茵曼旗舰店同款冬季加厚羽绒服","888.00","prodoctList_l_-29.jpg","prodoctList_s-29.jpg"),
	(NULL,"初语文艺棉质冬季清新纯棉衬衫","5436.00","prodoctList_l_-30.jpg","prodoctList_s-30.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"筱姿秋冬复古娃娃领绣花蝴蝶结","45.00","prodoctList_l_-18.jpg","prodoctList_s-18.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg"),
	(NULL,"棉立方韩版立领文艺绣花棉衬衣","98.00","prodoctList_l_-11.jpg","prodoctList_s-11.jpg"),
	(NULL,"初秋宽松口袋单排扣针织毛衣","48.00","prodoctList_l_-12.jpg","prodoctList_s-12.jpg"),
	(NULL,"新款大码女装针织衫女开衫","768.00","prodoctList_l_-13.jpg","prodoctList_s-13.jpg"),
	(NULL,"如曼卡春秋韩版宽松三粒扣毛衣","178.00","prodoctList_l_-14.jpg","prodoctList_s-14.jpg"),
	(NULL,"茵曼女士v领波点拼接毛衣","364.00","prodoctList_l_-15.jpg","prodoctList_s-15.jpg"),
	(NULL,"梅茵休闲时尚百搭短外套","64.00","prodoctList_l_-16.jpg","prodoctList_s-16.jpg"),
	(NULL,"恩兰朵波点长袖衬衫女衬衣","82.00","prodoctList_l_-17.jpg","prodoctList_s-17.jpg"),
	(NULL,"针织衫开衫女韩版薄短款","84.00","prodoctList_l_-22.jpg","prodoctList_s-22.jpg"),
	(NULL,"秋冬韩版修身撞色黑白a字裙 ","361.00","prodoctList_l_-23.jpg","prodoctList_s-23.jpg"),
	(NULL,"毛呢冬季欧美高端黑色打底a字裙","88.00","prodoctList_l_-24.jpg","prodoctList_s-24.jpg"),
	(NULL,"欧美七分袖时尚格子连衣裙","54.00","prodoctList_l_-25.jpg","prodoctList_s-25.jpg"),
	(NULL,"茵曼旗舰店女式纯棉打底衫","34.00","prodoctList_l_-26.jpg","prodoctList_s-26.jpg"),
	(NULL,"套头韩版秋冬半高领宽松外套","84.00","prodoctList_l_-27.jpg","prodoctList_s-27.jpg"),
	(NULL,"韩版短款毛呢外套半身裙  ","367.00","prodoctList_l_-28.jpg","prodoctList_s-28.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"茵曼纯棉文艺印花绣花衬衣","55.00","prodoctList_l_-2.jpg","prodoctList_s-2.jpg"),
	(NULL,"初语文艺衬衫女猫咪刺绣衬衣","123.00","prodoctList_l_-3.jpg","prodoctList_s-3.jpg"),
	(NULL,"妖精的口袋 趣味绣花衬衫女","453.00","prodoctList_l_-4.jpg","prodoctList_s-4.jpg"),
	(NULL,"KIKOT新款时尚简约长袖衬衫女","222.00","prodoctList_l_-5.jpg","prodoctList_s-5.jpg"),
	(NULL,"阔色韩版格子秋季百搭格纹衬衣","808.00","prodoctList_l_-6.jpg","prodoctList_s-6.jpg"),
	(NULL,"爽姿丽人秋冬韩版提花拼接","188.00","prodoctList_l_-7.jpg","prodoctList_s-7.jpg"),
	(NULL,"宿·色白衬衫长袖女装冬装新品","288.00","prodoctList_l_-8.jpg","prodoctList_s-8.jpg"),
	(NULL,"韩都衣舍韩版宽松刺绣立领衬衫","388.00","prodoctList_l_-9.jpg","prodoctList_s-9.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"米克伦牛仔衬衫女韩版长袖","48.00","prodoctList_l_-1.jpg","prodoctList_s-1.jpg"),
	(NULL,"乐瓣韩版polo领人物图案撞色衫","878.00","prodoctList_l_-10.jpg","prodoctList_s-10.jpg");
	

CREATE TABLE nv_cart(
	cid INT PRIMARY KEY AUTO_INCREMENT,
	userId INT
);
INSERT INTO nv_cart VALUES
	(NULL,125165),
	(NULL,125166);

CREATE TABLE nv_cart_details(
	did INT PRIMARY KEY AUTO_INCREMENT,
	cartId INT,
	productId INT,
	count INT,
	status INT
);
INSERT INTO nv_cart_details VALUES
	(NULL,1,12,3,1),
	(NULL,2,15,1,1);

CREATE TABLE nv_order(
	oid INT PRIMARY KEY AUTO_INCREMENT,
	pid INT,
	pname VARCHAR(35),
	price DOUBLE(8,2),
	pic_s VARCHAR(32),
	orderTime BIGINT,
	userId INT
);
INSERT INTO nv_order VALUES
	(15962188,"16","梅茵休闲时尚百搭短外套","88.88","prodoctList_s-16.jpg","2934512267890123","125165"),
	(NULL,"17","阔色韩版格子秋季百搭格纹衬衣","128.88","prodoctList_s-17.jpg","1934567891230","125165"),
	(NULL,"18","梅茵休闲时尚百搭短外套","128.88","prodoctList_s-18.jpg","293456789","125165"),
	(NULL,"19","阔色韩版格子秋季百搭格纹衬衣","128.88","prodoctList_s-19.jpg","293456789","125165"),
	(NULL,"12","梅茵休闲时尚百搭短外套","128.88","prodoctList_s-20.jpg","293456789","125165"),
	(NULL,"18","阔色韩版格子秋季百搭格纹衬衣","228.88","prodoctList_s-18.jpg","223456789","125166"),
	(NULL,"19","梅茵休闲时尚百搭短外套","888.88","prodoctList_s-19.jpg","223456789","125166");